# Generated by Django 6.0.6 on 2026-06-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آگهی')),
                ('property_type', models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('land', 'زمین'), ('office', 'اداری'), ('shop', 'مغازه')], max_length=20, verbose_name='نوع ملک')),
                ('status', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('pre_sale', 'پیش فروش')], max_length=20, verbose_name='وضعیت')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('deposit', models.BigIntegerField(blank=True, null=True, verbose_name='رهن')),
                ('rent', models.BigIntegerField(blank=True, null=True, verbose_name='اجاره')),
                ('area', models.PositiveIntegerField(verbose_name='متراژ')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='تعداد اتاق')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='طبقه')),
                ('year_built', models.PositiveIntegerField(verbose_name='سال ساخت')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('owner_name', models.CharField(max_length=100, verbose_name='نام مالک')),
                ('owner_phone', models.CharField(max_length=15, verbose_name='شماره مالک')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
