# Generated by Django 6.0 on 2026-06-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='hammam',
            field=models.CharField(max_length=100, null=True, verbose_name='تعداد حمام'),
        ),
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('فروش', 'فروش'), ('اجاره', 'اجاره'), ('پیش فروش', 'پیش فروش')], max_length=20, verbose_name='وضعیت'),
        ),
    ]
