# Generated by Django 6.0 on 2026-06-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_hammam_alter_home_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='hammam',
            field=models.IntegerField(max_length=100, null=True, verbose_name='تعداد حمام'),
        ),
    ]
