# Generated by Django 6.0.6 on 2026-07-12 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_home_hammam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.TextField(verbose_name='آدرس* '),
        ),
        migrations.AlterField(
            model_name='home',
            name='area',
            field=models.PositiveIntegerField(verbose_name='متراژ* '),
        ),
        migrations.AlterField(
            model_name='home',
            name='hammam',
            field=models.IntegerField(null=True, verbose_name='تعداد حمام'),
        ),
        migrations.AlterField(
            model_name='home',
            name='owner_name',
            field=models.CharField(max_length=100, verbose_name='نام مالک* '),
        ),
        migrations.AlterField(
            model_name='home',
            name='owner_phone',
            field=models.CharField(max_length=15, verbose_name='شماره مالک* '),
        ),
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.BigIntegerField(verbose_name='قیمت* '),
        ),
        migrations.AlterField(
            model_name='home',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('land', 'زمین'), ('office', 'اداری'), ('shop', 'مغازه')], max_length=20, verbose_name='نوع ملک* '),
        ),
        migrations.AlterField(
            model_name='home',
            name='rooms',
            field=models.PositiveSmallIntegerField(verbose_name='تعداد اتاق* '),
        ),
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(choices=[('فروش', 'فروش'), ('اجاره', 'اجاره'), ('پیش فروش', 'پیش فروش')], max_length=20, verbose_name='وضعیت* '),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان آگهی* '),
        ),
        migrations.AlterField(
            model_name='home',
            name='year_built',
            field=models.PositiveIntegerField(verbose_name='سال ساخت* '),
        ),
    ]
