# Generated by Django 6.0.6 on 2026-07-13 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_home_owner_alter_home_address_alter_home_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_home')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.home')),
            ],
        ),
    ]
